### ISSUE TITLE
interest in making this a cross platform project?

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/tonel#2]
I've just forked tonel to https://github.com/GsDevKit/tonel with the plan to port tonel to GemStone base image over the next few weeks. Since tonel is ulitimately intended to be a cross-platform file format I think a cross platform project would be preferred --- using travis to valid changes against ... a common package structure, etc. --- Presumably there is a fair amount of code that can be shared between platforms -- but I admit that I haven't delved too deep into the code to see just how portable it currently is...

If there is interest in making the pharo-vcs-tonel project cross platform then I will try to partition the packages/code while porting to the GemStone base image and to the GsDevKit project (upon which Seaside is based).

If there is no interest in hosting a cross-platform project, then I will undertake that task and break the forked relationship as there will be little in common other than a common starting point ...

**Comment by estebanlm** [comment]
hi @dalehenrich 
yes, the intention is to make it portable. Now, I tried to keep it as "portable" as possible, but I'm sure there are a lot of small things to change (we even needed to reintroduce a dependency with Pharo just now, to quick fix a problem, but we will restore the compatible code later).
Please, go ahead and propose all the changes you want :)

**Comment by dalehenrich** [comment]
@estebanlm, Excellent ... other than a few baseline changes I think you have done a good job of making the implementation portable for the Monticello-family ... It loaded into my GemStone/GsDevKit image without trouble --- haven't run tests yet:), but I would agree with you that there might be small things ...

I think there will be a bit more work involved when I port the implementation to [Cypress 1](https://github.com/dalehenrich/CypressReferenceImplementation) and eventually Cypress 2 (soon to be renamed) ... we'll have to abstract out the direct references to the Monticello definition classes (common api) and we'll be extending some of the properties with GemStone-specific properties ... but I think that it is doable ... it is nice that it is a small implementation -- good job!
