### ISSUE TITLE
problem when exporting on windows

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/tonel#20]
seems that the end of line exporting has problems since some invisible chars appears on end of method

**Comment by jecisc** [comment]
Here is an example:

https://github.com/pharo-project/pharo/pull/474/files

**Comment by jecisc** [comment]
What seems to change is that there are white space at the end of lines deleted.

**Comment by jecisc** [comment]
The problem seems to come from:
`TonelScanner>>removeFrom:enclosingStart:end:clean:`

**Comment by jecisc** [comment]
When I add a halt in this method, I see that the string contains only lf and not crlf. The code seems to check the size of the current platform line ending. So it expect to skip two line return characters but only find one. It will skip all separators...

**Comment by jecisc** [comment]
So either `LGitTreeEntry>>readStreamDo:` should give a stream with the current platform lines ending or `TonelScanner>>removeFrom:enclosingStart:end:clean:` should be improve to manage the case where we are on windows and there is only lf in the stream.

**Comment by jecisc** [comment]
@estebanlm If the clean solution is the first one, the code becomes too complicated for me to dig in more :)
