### ISSUE TITLE
Tonel format differences in Pharo 6.1 and 7

### ISSUE THREAD

**Issue by gcotelli** [pharo-vcs/tonel#51]
When you commit packages in Tonel format for Pharo 6.1 and 7 the output is not the same.

For example:
#category : #'Boardwalk-Tests-Javascript'
#category : 'Boardwalk-Tests-Javascript'

A version gets the category as a String and the other as a Symbol.

**Comment by estebanlm** [comment]
this is not a bug, you need to update tonel in 6.1 :)
