### ISSUE TITLE
what is the benefit of using platform-specific line ending?

### ISSUE THREAD

**Issue by peteruhnak** [pharo-vcs/tonel#54]
Is there a good reason why Tonel uses platform-specific line ending?

```
TonelWriter>>newLine
	 ^ OSPlatform current lineEnding
```

It produces a lot of problems, and I don't see any advantage.

**Comment by estebanlm** [comment]
readability.
part of the objectives of tonel is to produce an external readable file.
using platform specific line ending guarantees sources will be seen in any platform.

**Comment by dalehenrich** [comment]
... but wait doesn't this cause unnecessary changes when a tonel file is being written cross platform? readability is destroyed in this case ... not sure that this is a good idea ... have you talked this over with @martinmcclure?

**Comment by jecisc** [comment]
On Windows the default setting for git is: checkout windows style, commit unix style. 

So no unwanted changes.

**Comment by peteruhnak** [comment]
Since when? Normally you need to enable this explicitly, which becomes a problem when you have mixed projects.

On Windows the default setting for git is: checkout windows style, commit unix style.
So no unwanted changes.

**Comment by jecisc** [comment]
It's the default option when installing git bash. There is a wizard with multiple choices and the one is the one checked by default.

**Comment by dalehenrich** [comment]
Martin confirms that platform-specific line endings are expected... This does imply that we should recommend/require a standard .gitattributes file (https://help.github.com/articles/dealing-with-line-endings/) for all repositories? It would make sense to include the Smalltalk lang  declaration (https://github.com/GemTalk/Rowan/blob/master/.gitattributes) while we are at it... if one already exists I’d like to know where it is so I can point to it:)
