### ISSUE TITLE
Sequence Dollar Dollar Bracket breaks tonal parser

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/tonel#57]
Following test fails:
```Smalltalk
TonelParserTest>>testMethodBodyWithDollarAndBracket
	self 
		assertParse: '[ [ $$] ]'
		rule: #methodBody
		equals: ' [ $$] '.
```
It shows problem with methods which return dollar character from block:
```Smalltalk
AClass>>someMethod
   true ifTrue: [^$$]
```
Notice that space between dollar and bracket works fine

**Comment by dionisiydk** [comment]
Possible fix:
```Smalltalk
TonelSourceScanner>>scanForBlockIfMatch: aBlock
	| match |
	
	match := false.
	(char = $[ and: [  prevChar ~= $$ ]) ifTrue: [ 
		count := count + 1.
		match := true ].
	(char = $] and: [ prevChar ~= $$ or: [ prevPrevChar = $$ ] ]) ifTrue: [ 
		count := count - 1.
		match := true ].
	count = 0 ifTrue: [ isFinished := true ].
	match ifTrue: aBlock
```

**Comment by pavel-krivanek** [comment]
already fixed in https://github.com/pharo-vcs/tonel/commit/0c2986f50309ae86cf836d3ce4155af8d485e995

**Comment by dalehenrich** [comment]
Haha ... this was the exact problem that we ran into Monday, that caused me to decide to use an RBParser based solution...

**Comment by estebanlm** [comment]
well, originally I did not use `RBParser` to make Tonel more portable. 
But since you are using it for your implementation, we can replace this part of tonel with a new, better implementation :)

**Comment by estebanlm** [comment]
but anyway, if this is fixed, then we can close this.
