### ISSUE TITLE
Can we add in the readme how to convert from filetree to tonel?

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/tonel#61]
After 20 min looking for it I still do not find it. 
I'm stupid for sure.

**Comment by jecisc** [comment]
It is done in Iceberg there:

https://github.com/pharo-vcs/iceberg/blob/master/Iceberg-Plugin-Migration.package/IceConvertFormatAction.class/instance/migrateSources.st

**Comment by simonfranz** [comment]
is there any option through the gui?

**Comment by estebanlm** [comment]
yes, in the "extras" section.
