### ISSUE TITLE
Conversion from filetree to tonel: package wrongly converted

### ISSUE THREAD

**Issue by jbrichau** [pharo-vcs/tonel#74]
When trying to convert Seaside (https://github.com/SeasideSt/Seaside) sources to tonel, the converted repository is not correct. 
For example, the `Seaside-Tests-Component` cannot be found. I notice this package has no classes directly defined in `Seaside-Tests-Component` but only in subcategories. There are, however, package extensions defined in `Seaside-Tests-Component`.

The converter created a package `Seaside-Tests-Component-Stubs` rather than `Seaside-Tests-Component`.  See https://github.com/SeasideSt/Seaside/tree/master-tonel/repository

To test:
- Clone Seaside repo
- Use 'convert sources to tonel' in Iceberg
- Load 'CI' metacello group from the repo in tonel format
-> error 'Could not resolve Seaside-Tests-Component'

**Comment by astares** [comment]
This one seems to be problematic for other issues as well 
https://github.com/astares/Seaside-Bootstrap/issues/9

**Comment by bencoman** [comment]
Has the fix been integrated into Pharo 8?

**Comment by estebanlm** [comment]
I have no idea :)
@guillep this was in 1.6.0?

**Comment by guillep** [comment]
No it was not because nobody integrated the PR. Iceberg's 1.6.0 had only what was already integrated. I'll integrate it now and make it for 1.7.0

**Comment by jbrichau** [comment]
This issue can be closed. I have done the conversion to tonel again in Pharo9 for the Seaside repository and it seems to be all OK. At the very least, this issue is no longer there.
