### ISSUE TITLE
Do you guarantee the the class metaData does not contain a `{` or `}`?

### ISSUE THREAD

**Issue by dalehenrich** [pharo-vcs/tonel#8]
Just stepping through the parser as it reads meta data and I see that it is simply counting  `{` and `}`, so it is vulnerable to either one of those characters embedded in the meta data itself (including symbols) ...

**Comment by estebanlm** [comment]
yes it is.
but so far we do not have metadata that includes { } so I didn't implement a solution to solve that. So far, we are ok and most of our projects are already running on tonel, but do not hesitate to open an issue as "bug" or "feature" if this proves wrong.
