### ISSUE TITLE
Read/write problem when a method has certain "unfinished statements"

### ISSUE THREAD

**Issue by tinchodias** [pharo-vcs/tonel#93]
# In short

The IDE doesn't stop the user to save and commit a method with more `]`s than `[`s (an `RBUnfinishedStatementErrorNode` in the AST). The problem is that Tonel can't read correctly that .st file in that commit. It only partially reads the method with the "unfinished statement", and the following methods are misread.

# History / Evidence

This started with a commit in Roassal3 that wasn't loading. Also the diff looked very weird in Iceberg:

![Iceberg tree](https://user-images.githubusercontent.com/3044265/104496352-a1641900-55b7-11eb-92c2-3436a34aacd8.png)

After investigation, we spotted the extra `]` in a method:

![Source code](https://user-images.githubusercontent.com/3044265/104490484-a9b85600-55af-11eb-873e-8238b649294d.png)

[You can see it here](https://github.com/ObjectProfile/Roassal3/commit/902231cdb1b6a4aaf57b77c83724c0a1e36e47c2#diff-d272ce4891976a79076779b87f173b3c2f47c83ecd85c12dc46330ebba465a34R400)

# Steps to Reproduce

In Pharo 9 (downloaded Jan 12th):
1. Create a new class `TmpNewClass` in a new package `Tmp`
2. Compile these 2 tiny methods: `tonelDestroyer [ ] ]` and `tonelZ ^'z'`
3. In Iceberg, create a temporary repository.
4. Select the new repository, click on "Add package" and add the `Tmp` package.
5. Commit and browse the diff.

Before commit:
<img width="685" alt="Screen Shot 2021-01-13 at 15 20 01" src="https://user-images.githubusercontent.com/3044265/104496106-4cc09e00-55b7-11eb-8440-3c74e3ce1f1f.png">

After commit (immediately after pressing the commit button):
<img width="576" alt="Screen Shot 2021-01-13 at 15 20 35" src="https://user-images.githubusercontent.com/3044265/104496677-07e93700-55b8-11eb-8044-59af71dd572e.png">

**Comment by guillep** [comment]
I chased this up to build 817 of Pharo.
It seems to be a side effect of my changes to parse the senders and implementors:

https://github.com/pharo-project/pharo/commit/3f758fb9b0fc00deaffdcf26d2772e34f4ba6dbe

It’s not allowing any invalid code, only “closers” at the end of the method (parenthesis and brackets).
I’ll fix it and write a couple of tests for this. We should test that the parser consumes the entire stream.
We should migrate this issue to Pharo.

**Comment by tinchodias** [comment]
It's fixed by this PR: https://github.com/pharo-project/pharo/pull/8367

**Comment by tinchodias** [comment]
I close it now that the above-mentioned PR is merged into Pharo 9.
