### ISSUE TITLE
TonelWriter uses the platform line ending

### ISSUE THREAD

**Issue by gcotelli** [pharo-vcs/tonel#99]
`TonelWriter` uses the platform line ending convention when writing new lines. This is problematic for projects with contributors using different OS versions. 
I have been bitted more than once with Pull Requests made from people using Windows because every little file looks like changed due to line endings. 
I think it's better to settle into ONE line-ending convention for all the platforms. Any decent editor can read any of the line-ending formats so I don't see a problem here, and it will make project maintainers happier :smile: .
I propose to use the UNIX line-ending format given that is the native one in 2 of the 3 supported platforms.

**Comment by estebanlm** [comment]
indeed, as Martin says. 
You can always configure git to avoid this problems. See https://github.com/pharo-project/pharo/blob/Pharo10/.gitattributes as an example.
